### ISSUE TITLE
AllowedCurrenciesForNO wrong format

### ISSUE THREAD

**Issue by alixodendhal** [nium-global/nium-n1-beneficiary-service#6]
There is an issue with the [payment accounts yaml line:450](https://github.com/nium-global/nium-n1-beneficiary-service/blob/main/payment-accounts.yaml#L450), is not the right format. See below. 

### snippet
```yaml
DK: '#/components/schemas/AllowedCurrenciesForDK'
SE: '#/components/schemas/AllowedCurrenciesForSE'
GB: '#/components/schemas/AllowedCurrenciesForGB'
HR: '#/components/schemas/AllowedCurrenciesForHR'
JP: '#/components/schemas/AllowedCurrenciesForJP'
"NO": '#/components/schemas/AllowedCurrenciesForNO'
PL: '#/components/schemas/AllowedCurrenciesForPL'
RO: '#/components/schemas/AllowedCurrenciesForRO'
BG: '#/components/schemas/AllowedCurrenciesForBG'
CZ: '#/components/schemas/AllowedCurrenciesForCZ'
```
